#!/usr/bin/env python3

"""
Candidate → Lukhas promotion helper (safe, auditable).

Features:
- Copy a module or package from `candidate/` into `lukhas/` preserving layout
- Rewrite intra-repo imports: `from lukhas.` → `from lukhas.`
- Optional shim module to preserve legacy imports during transition
- Dry-run mode and human-readable report

Usage:
  python tools/scripts/promote_module.py \
      --src candidate/core/orchestration \
      --dst lukhas/core/orchestration \
      [--shim-direction candidate->lukhas|lukhas->candidate] \
      [--dry-run]

Notes:
- This does not delete anything in `candidate/`.
- Run tests/smoke before and after; see AUTHORATIVE_PROMOTION_PROCESS.md
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

REWRITE_IMPORT = re.compile(r"\bfrom\s+candidate\.(?P<rest>\S+)\s+import\s")
REWRITE_IMPORT2 = re.compile(r"\bimport\s+candidate(?P<rest>(\.|\s).*)")


@dataclass
class PromotionResult:
    copied_files: list[str]
    rewritten_files: list[str]
    shim_file: str | None
    dry_run: bool


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Promote module from candidate to lukhas")
    p.add_argument("--src", required=True, help="Source path under candidate/")
    p.add_argument("--dst", required=True, help="Destination under lukhas/")
    p.add_argument("--dry-run", action="store_true", help="Show actions without writing")
    p.add_argument(
        "--shim-direction",
        choices=["candidate->lukhas", "lukhas->candidate"],
        default=None,
        help="Create a transitional shim module to ease imports",
    )
    return p.parse_args()


def ensure_parent(path: Path, dry: bool) -> None:
    if not dry:
        path.parent.mkdir(parents=True, exist_ok=True)


def copy_tree(src: Path, dst: Path, dry: bool) -> list[str]:
    files: list[str] = []
    if src.is_file():
        ensure_parent(dst, dry)
        files.append(str(dst))
        if not dry:
            shutil.copy2(src, dst)
        return files

    for p in src.rglob("*"):
        rel = p.relative_to(src)
        out = dst / rel
        if p.is_dir():
            if not dry:
                out.mkdir(parents=True, exist_ok=True)
            continue
        # Skip caches and tests by default; promote tests later explicitly
        if any(x in str(p) for x in ("__pycache__", ".pytest_cache")):
            continue
        ensure_parent(out, dry)
        files.append(str(out))
        if not dry:
            shutil.copy2(p, out)
    return files


def rewrite_imports(dst_root: Path, files: Iterable[str], dry: bool) -> list[str]:
    rewritten: list[str] = []
    for f in files:
        if not f.endswith(".py"):
            continue
        path = Path(f)
        try:
            text = path.read_text(encoding="utf-8") if path.exists() else ""
        except Exception:
            continue

        new = REWRITE_IMPORT.sub(r"from lukhas.\g<rest> import ", text)
        new = REWRITE_IMPORT2.sub(r"import lukhas\g<rest>", new)
        if new != text:
            rewritten.append(str(path))
            if not dry:
                path.write_text(new, encoding="utf-8")
    return rewritten


def create_shim(shim_direction: str | None, src: Path, dst: Path, dry: bool) -> str | None:
    if not shim_direction:
        return None

    shim_file: Path
    if shim_direction == "candidate->lukhas":
        # Create a candidate shim that re-exports from lukhas
        # Example: candidate/core/orchestration/__init__.py -> from lukhas.core.orchestration import *
        shim_file = src / "__init__.py"
        content = _shim_content("lukhas", src)
    else:
        # Create a lukhas shim that re-exports from candidate (rare; transitional)
        shim_file = dst / "__init__.py"
        content = _shim_content("labs", dst)

    if not dry:
        shim_file.parent.mkdir(parents=True, exist_ok=True)
        with open(shim_file, "w", encoding="utf-8") as f:
            f.write(content)
    return str(shim_file)


def _shim_content(target_root: str, module_path: Path) -> str:
    # Derive dotted path under root from provided path
    # e.g., lukhas/core/orchestration -> lukhas.core.orchestration
    parts = list(module_path.parts)
    try:
        idx = parts.index(target_root)
    except ValueError:
        # Fallback: best-effort
        dotted = target_root
    else:
        dotted = ".".join(parts[idx:])
    return (
        "# Transitional shim generated by promote_module.py\n"
        "# NOTE: remove this shim once dependents migrate.\n"
        f"from {dotted} import *  # noqa\n"
    )


def main() -> int:
    args = parse_args()

    src = Path(args.src).resolve()
    dst = Path(args.dst).resolve()

    if "labs" not in src.parts or "lukhas" not in dst.parts:
        print(
            "❌ Expected --src under candidate/ and --dst under lukhas/",
            file=sys.stderr,
        )
        return 2

    if not src.exists():
        print(f"❌ Source does not exist: {src}", file=sys.stderr)
        return 2

    copied = copy_tree(src, dst, args.dry_run)
    rewritten = rewrite_imports(dst, copied, args.dry_run)
    shim = create_shim(args.shim_direction, src, dst, args.dry_run)

    PromotionResult(
        copied_files=copied,
        rewritten_files=rewritten,
        shim_file=shim,
        dry_run=args.dry_run,
    )

    # Emit a report for auditors
    out_dir = Path(".lukhas_audit")
    out_dir.mkdir(exist_ok=True)
    report_path = out_dir / "promotion_report.json"
    payload = {
        "src": str(src),
        "dst": str(dst),
        "dry_run": args.dry_run,
        "copied_count": len(copied),
        "rewritten_count": len(rewritten),
        "shim_file": shim,
    }
    if not args.dry_run:
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

    # Summary
    print("📦 Promotion summary")
    print(f"  Copied:    {len(copied)} files")
    print(f"  Rewritten: {len(rewritten)} files (imports updated)")
    if shim:
        print(f"  Shim:      {shim}")
    print(f"  Dry-run:   {args.dry_run}")
    if args.dry_run:
        print("(no files written)")
    else:
        print(f"📝 Report:   {report_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
