from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class AGIMemoryProtocol(Protocol):
    def put(self, key: str, value: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def fold_open(self, *, parent_id: Optional[str] = None) -> str: ...
    def fold_append(self, fold_id: str, item: Any) -> None: ...
    def fold_close(self, fold_id: str) -> dict: ...
