#!/usr/bin/env python3
"""
Generate progress reports from MASTER_LOG.md.

Usage:
    python3 scripts/todo/generate_reports.py [--type weekly] [--output reports/]

Generates reports:
- Weekly progress summary
- Agent productivity metrics
- Priority health check
- Completion rate analysis

Options:
    --type: Report type (weekly, monthly, agent, health)
    --output: Output directory (default: TODO/reports/)
"""

import argparse
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List

# ANSI colors
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"


class ReportGenerator:
    """Generate progress reports from MASTER_LOG."""

    def __init__(self, output_dir: str = "TODO/reports"):
        self.master_log_path = Path("TODO/MASTER_LOG.md")
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

        self.tasks = []
        self.stats = {}

    def generate(self, report_type: str = "weekly"):
        """Generate specified report type."""
        if not self.master_log_path.exists():
            print(f"{RED}MASTER_LOG not found: {self.master_log_path}{RESET}")
            return

        # Parse MASTER_LOG
        self._parse_master_log()
        self._calculate_stats()

        # Generate report based on type
        if report_type == "weekly":
            self._generate_weekly_report()
        elif report_type == "monthly":
            self._generate_monthly_report()
        elif report_type == "agent":
            self._generate_agent_report()
        elif report_type == "health":
            self._generate_health_report()
        else:
            print(f"{RED}Unknown report type: {report_type}{RESET}")

    def _parse_master_log(self):
        """Parse MASTER_LOG and extract tasks."""
        # Simplified parsing - would need full implementation
        content = self.master_log_path.read_text()

        # Extract stats from Quick Stats section
        import re
        total_match = re.search(r'Total Tasks:\s*(\d+)', content)
        completed_match = re.search(r'Completed:\s*(\d+)', content)
        active_match = re.search(r'Active:\s*(\d+)', content)

        if total_match:
            self.stats['total'] = int(total_match.group(1))
        if completed_match:
            self.stats['completed'] = int(completed_match.group(1))
        if active_match:
            self.stats['active'] = int(active_match.group(1))

    def _calculate_stats(self):
        """Calculate additional statistics."""
        if 'total' in self.stats and 'completed' in self.stats:
            total = self.stats['total']
            completed = self.stats['completed']
            self.stats['completion_rate'] = (
                (completed / total * 100) if total > 0 else 0
            )

    def _generate_weekly_report(self):
        """Generate weekly progress report."""
        today = datetime.now()
        week_start = today - timedelta(days=7)

        report_path = self.output_dir / f"weekly_{today.strftime('%Y-%m-%d')}.md"

        content = f"""# LUKHAS TODO Weekly Progress Report

**Report Date**: {today.strftime('%Y-%m-%d')}
**Period**: {week_start.strftime('%Y-%m-%d')} to {today.strftime('%Y-%m-%d')}

---

## Summary

- **Total Tasks**: {self.stats.get('total', 0)}
- **Completed**: {self.stats.get('completed', 0)}
- **Active**: {self.stats.get('active', 0)}
- **Completion Rate**: {self.stats.get('completion_rate', 0):.1f}%

---

## This Week's Achievements

*Requires manual update based on completed tasks with recent dates*

---

## Next Week's Focus

**Priority 0 Tasks**: *Review MASTER_LOG P0 section*

**Priority 1 Tasks**: *Review MASTER_LOG P1 section*

---

## Agent Productivity

*To be calculated from agent task completion*

- **CODEX**: X tasks completed
- **Jules**: X tasks completed
- **Claude Code**: X tasks completed
- **Copilot**: X tasks completed

---

## Health Indicators

- **P0 tasks age**: ⚠️ Check for any P0 tasks >1 day old
- **P1 completion rate**: Target 80% weekly
- **Blocked tasks**: {self.stats.get('blocked', 0)} tasks

---

## Recommendations

*Auto-generated recommendations based on metrics*

---

**Report generated by**: `scripts/todo/generate_reports.py`
**Data source**: TODO/MASTER_LOG.md
"""

        report_path.write_text(content)
        print(f"{GREEN}✓{RESET} Weekly report generated: {report_path}")

    def _generate_monthly_report(self):
        """Generate monthly summary report."""
        print(f"{YELLOW}Monthly report generation not yet implemented{RESET}")

    def _generate_agent_report(self):
        """Generate agent productivity report."""
        print(f"{YELLOW}Agent report generation not yet implemented{RESET}")

    def _generate_health_report(self):
        """Generate TODO system health report."""
        today = datetime.now()
        report_path = self.output_dir / f"health_{today.strftime('%Y-%m-%d')}.md"

        # Calculate health score
        completion_rate = self.stats.get('completion_rate', 0)
        total = self.stats.get('total', 0)
        active = self.stats.get('active', 0)

        # Simple health scoring
        if completion_rate > 80:
            health_status = f"{GREEN}EXCELLENT{RESET}"
            health_emoji = "✅"
        elif completion_rate > 50:
            health_status = f"{BLUE}GOOD{RESET}"
            health_emoji = "👍"
        elif completion_rate > 20:
            health_status = f"{YELLOW}NEEDS ATTENTION{RESET}"
            health_emoji = "⚠️"
        else:
            health_status = f"{RED}CRITICAL{RESET}"
            health_emoji = "🚨"

        content = f"""# TODO System Health Report

**Report Date**: {today.strftime('%Y-%m-%d %H:%M')}

---

## Overall Health: {health_emoji} {health_status}

---

## Key Metrics

| Metric | Value | Status |
|--------|-------|--------|
| Total Tasks | {total} | - |
| Active Tasks | {active} | {'⚠️ High' if active > 100 else '✅ Normal'} |
| Completion Rate | {completion_rate:.1f}% | {health_emoji} |

---

## Recommendations

"""

        if completion_rate < 20:
            content += "- 🚨 **URGENT**: Very low completion rate. Review and close completed tasks.\n"
        if active > 100:
            content += "- ⚠️ **HIGH**: Too many active tasks. Consider archiving or closing stale tasks.\n"
        if completion_rate > 80:
            content += "- ✅ **EXCELLENT**: Maintain current momentum!\n"

        content += "\n---\n\n**Report generated by**: `scripts/todo/generate_reports.py`\n"

        report_path.write_text(content)
        print(f"{GREEN}✓{RESET} Health report generated: {report_path}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='Generate TODO progress reports')
    parser.add_argument(
        '--type',
        choices=['weekly', 'monthly', 'agent', 'health'],
        default='weekly',
        help='Report type to generate'
    )
    parser.add_argument(
        '--output',
        default='TODO/reports',
        help='Output directory for reports'
    )

    args = parser.parse_args()

    generator = ReportGenerator(output_dir=args.output)
    generator.generate(report_type=args.type)


if __name__ == "__main__":
    main()
