#!/usr/bin/env python3
"""
Create __init__.py files in package directories that contain python modules but lack __init__.py.
Skips certain directories like release_artifacts and .git. Idempotent.
"""
from pathlib import Path

ROOT = Path(".")
EXCLUDED = ("release_artifacts", ".git", "__pycache__")

def main():
    count = 0
    for d in ROOT.rglob("*"):
        if not d.is_dir():
            continue
        s = str(d)
        if any(ex in s for ex in EXCLUDED):
            continue
        py_files = list(d.glob("*.py"))
        if py_files and not (d / "__init__.py").exists():
            (d / "__init__.py").write_text("# autogenerated package init\n", encoding="utf-8")
            print(f"[ADD INIT] {d}")
            count += 1
    print(f"Created __init__.py in {count} directories.")

if __name__ == "__main__":
    main()
