#!/bin/bash
# LUKHAS AI Cleanup Script
# Generated by cleanup_analysis.py
# Trinity Framework: ⚛️🧠🛡️

set -e  # Exit on error

ARCHIVE_DIR="/Users/agi_dev/lukhas-archive/2025-08-13-cleanup"
mkdir -p "$ARCHIVE_DIR"

echo "🧹 Starting LUKHAS AI cleanup..."


# Archive agent workspaces (isolated experiments)
echo "📦 Archiving agent workspaces..."
mkdir -p "$ARCHIVE_DIR/agent_workspaces"
mv "CLAUDE_ARMY/CLAUDE_ARMY/workspaces/testing-devops-specialist/tests/test_mvp.py" "$ARCHIVE_DIR/agent_workspaces/" 2>/dev/null || true
mv "CLAUDE_ARMY/workspaces/consent-compliance-specialist/src/consent_ledger.py" "$ARCHIVE_DIR/agent_workspaces/" 2>/dev/null || true
mv "CLAUDE_ARMY/workspaces/identity-auth-specialist/src/lambda_id.py" "$ARCHIVE_DIR/agent_workspaces/" 2>/dev/null || true
mv "CLAUDE_ARMY/workspaces/special-ops-secrets-kms-legacy/tools/sbom.py" "$ARCHIVE_DIR/agent_workspaces/" 2>/dev/null || true

# Archive NIAS theory files (experimental)
echo "🔬 Archiving NIAS theory files..."
mkdir -p "$ARCHIVE_DIR/nias_theory"
mv "NIAS_THEORY/NIAS_O1_COMPLETE/context_builder.py" "$ARCHIVE_DIR/nias_theory/" 2>/dev/null || true
mv "NIAS_THEORY/NIAS_O1_COMPLETE/nias_core.py" "$ARCHIVE_DIR/nias_theory/" 2>/dev/null || true
mv "NIAS_THEORY/NIAS_O1_COMPLETE/nias_mode.py" "$ARCHIVE_DIR/nias_theory/" 2>/dev/null || true
mv "NIAS_THEORY/NIAS_O1_COMPLETE/symbolic_matcher.py" "$ARCHIVE_DIR/nias_theory/" 2>/dev/null || true

# Archive duplicate API implementations
echo "🔄 Archiving duplicate APIs..."
mkdir -p "$ARCHIVE_DIR/duplicate_apis"
mv "api/consciousness_chat_api.py" "$ARCHIVE_DIR/duplicate_apis/" 2>/dev/null || true
mv "api/feedback_api.py" "$ARCHIVE_DIR/duplicate_apis/" 2>/dev/null || true
mv "api/universal_language_api.py" "$ARCHIVE_DIR/duplicate_apis/" 2>/dev/null || true

echo "✅ Cleanup complete!"
echo "📊 Files archived to: $ARCHIVE_DIR"
echo "💾 Run 'git status' to see changes"
