#!/usr/bin/env python3
"""
Claude API Configuration Script

Interactive script to help configure Claude API access in LUKHAS.

Features:
- Validates API key format
- Tests API connectivity
- Updates .env file securely
- Optional macOS Keychain storage
- Provides troubleshooting guidance

Usage:
    python3 scripts/configure_claude_api.py
    python3 scripts/configure_claude_api.py --key sk-ant-YOUR_KEY
    python3 scripts/configure_claude_api.py --keychain  # Store in macOS Keychain
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
import re


def print_header(text: str):
    """Print formatted header"""
    print("\n" + "=" * 60)
    print(text)
    print("=" * 60 + "\n")


def print_success(text: str):
    """Print success message"""
    print(f"✅ {text}")


def print_error(text: str):
    """Print error message"""
    print(f"❌ {text}")


def print_info(text: str):
    """Print info message"""
    print(f"ℹ️  {text}")


def validate_api_key(key: str) -> bool:
    """
    Validate Anthropic API key format

    Args:
        key: API key to validate

    Returns:
        bool: True if valid format
    """
    # Anthropic keys start with sk-ant- and are followed by alphanumeric characters
    pattern = r'^sk-ant-[a-zA-Z0-9_-]+$'
    return bool(re.match(pattern, key))


def get_env_file_path() -> Path:
    """Get path to .env file"""
    repo_root = Path(__file__).parent.parent
    return repo_root / ".env"


def read_env_file() -> dict:
    """Read existing .env file"""
    env_path = get_env_file_path()

    if not env_path.exists():
        return {}

    env_vars = {}
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()

    return env_vars


def update_env_file(key: str, value: str):
    """
    Update or add key in .env file

    Args:
        key: Environment variable name
        value: Environment variable value
    """
    env_path = get_env_file_path()

    # Read existing content
    if env_path.exists():
        with open(env_path) as f:
            lines = f.readlines()
    else:
        lines = []

    # Update or add key
    found = False
    updated_lines = []

    for line in lines:
        if line.strip().startswith(f"{key}="):
            updated_lines.append(f"{key}={value}\n")
            found = True
        else:
            updated_lines.append(line)

    if not found:
        # Add new key (with comment header if file is new)
        if not updated_lines:
            updated_lines.append("# LUKHAS AI Environment Configuration\n")
            updated_lines.append("# Generated by configure_claude_api.py\n\n")

        updated_lines.append(f"# Anthropic API Key: https://console.anthropic.com/\n")
        updated_lines.append(f"{key}={value}\n")

    # Write back
    with open(env_path, 'w') as f:
        f.writelines(updated_lines)

    print_success(f"Updated {env_path}")


def store_in_keychain(api_key: str) -> bool:
    """
    Store API key in macOS Keychain

    Args:
        api_key: API key to store

    Returns:
        bool: True if successful
    """
    try:
        user = os.getenv('USER')
        service = "LUKHAS_ANTHROPIC_API_KEY"

        # Delete existing entry if present
        subprocess.run(
            ['security', 'delete-generic-password',
             '-a', user,
             '-s', service],
            capture_output=True,
            check=False  # Don't fail if entry doesn't exist
        )

        # Add new entry
        result = subprocess.run(
            ['security', 'add-generic-password',
             '-a', user,
             '-s', service,
             '-w', api_key],
            capture_output=True,
            text=True,
            check=True
        )

        return result.returncode == 0

    except subprocess.CalledProcessError as e:
        print_error(f"Keychain error: {e}")
        return False
    except Exception as e:
        print_error(f"Failed to store in keychain: {e}")
        return False


def retrieve_from_keychain() -> str | None:
    """
    Retrieve API key from macOS Keychain

    Returns:
        str | None: API key if found, None otherwise
    """
    try:
        user = os.getenv('USER')
        service = "LUKHAS_ANTHROPIC_API_KEY"

        result = subprocess.run(
            ['security', 'find-generic-password',
             '-a', user,
             '-s', service,
             '-w'],
            capture_output=True,
            text=True,
            check=True
        )

        return result.stdout.strip()

    except subprocess.CalledProcessError:
        return None
    except Exception:
        return None


async def test_api_key(api_key: str) -> bool:
    """
    Test API key with actual API call

    Args:
        api_key: API key to test

    Returns:
        bool: True if key works
    """
    try:
        # Set environment variable temporarily
        os.environ['ANTHROPIC_API_KEY'] = api_key

        # Import wrapper (will use the environment variable)
        sys.path.insert(0, str(Path(__file__).parent.parent))
        from bridge.llm_wrappers.anthropic_wrapper import AnthropicWrapper

        # Test generation
        claude = AnthropicWrapper()

        if not claude.is_available():
            return False

        response, model = await claude.generate_response(
            prompt="Say 'test' in one word.",
            model="claude-3-5-haiku-20241022",  # Fastest for testing
            max_tokens=10
        )

        return bool(response)

    except Exception as e:
        print_error(f"API test failed: {e}")
        return False


def interactive_setup():
    """Interactive configuration wizard"""
    print_header("🤖 Claude API Configuration for LUKHAS")

    print("This wizard will help you configure Claude API access.\n")

    # Step 1: Check for existing key
    print_info("Step 1: Checking for existing configuration...\n")

    env_vars = read_env_file()
    existing_key = env_vars.get('ANTHROPIC_API_KEY')

    if existing_key and existing_key != "sk-ant-REPLACE_WITH_YOUR_KEY":
        print_success(f"Found existing API key: {existing_key[:20]}...")
        replace = input("\nReplace existing key? (y/N): ").strip().lower()

        if replace != 'y':
            print_info("Configuration cancelled")
            return

    # Step 2: Get API key
    print_info("\nStep 2: Enter your Anthropic API key")
    print("         (Get one at: https://console.anthropic.com/)\n")

    while True:
        api_key = input("API Key (sk-ant-...): ").strip()

        if not api_key:
            print_error("API key cannot be empty")
            continue

        if not validate_api_key(api_key):
            print_error("Invalid API key format. Must start with 'sk-ant-'")
            retry = input("Try again? (Y/n): ").strip().lower()
            if retry == 'n':
                return
            continue

        break

    # Step 3: Test API key
    print_info("\nStep 3: Testing API key...\n")

    import asyncio
    test_passed = asyncio.run(test_api_key(api_key))

    if test_passed:
        print_success("API key is valid and working!")
    else:
        print_error("API key test failed. Key may be invalid or revoked.")
        proceed = input("\nSave anyway? (y/N): ").strip().lower()
        if proceed != 'y':
            print_info("Configuration cancelled")
            return

    # Step 4: Storage options
    print_info("\nStep 4: Choose storage method\n")

    print("Options:")
    print("  1. .env file (recommended for development)")
    print("  2. macOS Keychain (most secure)")
    print("  3. Both")

    choice = input("\nChoice (1-3): ").strip()

    if choice in ['1', '3']:
        update_env_file('ANTHROPIC_API_KEY', api_key)

    if choice in ['2', '3']:
        if store_in_keychain(api_key):
            print_success("Stored in macOS Keychain")
        else:
            print_error("Failed to store in Keychain")

    # Step 5: Verification
    print_header("✅ Configuration Complete")

    print("Your Claude API is now configured!\n")
    print("Next steps:")
    print("  1. Test integration:")
    print("     python3 scripts/test_claude_api.py")
    print()
    print("  2. See usage examples:")
    print("     python3 examples/claude_api_usage.py")
    print()
    print("  3. Read documentation:")
    print("     docs/bridge/CLAUDE_API_SETUP.md")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Configure Claude API access for LUKHAS"
    )
    parser.add_argument(
        "--key",
        help="API key to configure (sk-ant-...)"
    )
    parser.add_argument(
        "--keychain",
        action="store_true",
        help="Store in macOS Keychain"
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Test existing configuration"
    )

    args = parser.parse_args()

    # Test mode
    if args.test:
        print_header("🧪 Testing Claude API Configuration")

        env_vars = read_env_file()
        api_key = env_vars.get('ANTHROPIC_API_KEY')

        if not api_key or api_key == "sk-ant-REPLACE_WITH_YOUR_KEY":
            print_error("No API key configured in .env file")
            print_info("Run: python3 scripts/configure_claude_api.py")
            sys.exit(1)

        print_info(f"Found API key: {api_key[:20]}...")

        import asyncio
        test_passed = asyncio.run(test_api_key(api_key))

        if test_passed:
            print_success("API key is valid and working!")
            sys.exit(0)
        else:
            print_error("API key test failed")
            sys.exit(1)

    # Non-interactive mode with --key
    if args.key:
        if not validate_api_key(args.key):
            print_error("Invalid API key format")
            sys.exit(1)

        if args.keychain:
            if store_in_keychain(args.key):
                print_success("Stored in macOS Keychain")
            else:
                print_error("Failed to store in Keychain")
                sys.exit(1)
        else:
            update_env_file('ANTHROPIC_API_KEY', args.key)

        print_success("API key configured")
        sys.exit(0)

    # Interactive mode (default)
    interactive_setup()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏸️  Configuration cancelled by user")
        sys.exit(0)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
