#!/usr/bin/env python3
"""
Create Jules session for T4 Batch2D try-except codemod
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from bridge.llm_wrappers.jules_wrapper import JulesClient


async def create_codemod_session():
    """Create Jules session for try-except conversion"""

    prompt = """**P1 CODE QUALITY: Convert try-except ImportError to importlib.util.find_spec**

**Objective**: Systematic conversion of try-except import patterns to modern importlib checks

**Background**:
The codebase has many try-except ImportError patterns for optional dependencies:
```python
try:
    import optional_module
except ImportError:
    optional_module = None
```

This should be converted to:
```python
import importlib.util
if importlib.util.find_spec('optional_module'):
    import optional_module
else:
    optional_module = None
```

**Existing Infrastructure**:
- Script: `scripts/t4_batch2d_beta_runner.sh` (ready to use)
- Codemod: `tools/ci/codemods/convert_try_except_imports.py` (LibCST)
- File list: Generated by batch runner

**Task: Execute or Improve the Codemod**

**Option A: Run Existing Script** (Recommended)
```bash
# Generate candidate list first
./scripts/t4_batch2d_runner.sh

# Run codemod dry-run
./scripts/t4_batch2d_beta_runner.sh

# Review and apply
./scripts/t4_batch2d_beta_runner.sh --apply
```

**Option B: Improve Codemod** (If needed)
Review `tools/ci/codemods/convert_try_except_imports.py` and enhance:
1. Handle nested try-except patterns
2. Handle multiple imports in single try block
3. Preserve comments
4. Handle aliased imports (import X as Y)

**Pattern Examples to Handle**:

```python
# Pattern 1: Simple (MUST support)
try:
    import anthropic
except ImportError:
    anthropic = None

# Pattern 2: Multiple imports
try:
    import anthropic
    from openai import OpenAI
except ImportError:
    anthropic = None
    OpenAI = None

# Pattern 3: With as
try:
    import libcst as cst
except ImportError:
    cst = None

# Pattern 4: From import
try:
    from typing import Optional
except ImportError:
    Optional = None
```

**Conversion Strategy**:

For each pattern:
1. Extract imported module/names
2. Add `import importlib.util` at top if not present
3. Convert to if/else structure
4. Preserve variable assignments
5. Keep comments if any

**Safety Requirements**:
- Create backups before modification
- Verify syntax after transformation
- Run ruff cleanup
- Test files still compile
- Generate diff for review

**Expected Output**:

Files modified:
- Multiple .py files with try-except patterns in import region
- Each file backed up to `codemod_backups/`
- Clean diffs showing transformation

Verification:
- All files compile successfully
- Ruff F401 cleanup applied
- Git commit created with detailed message
- Draft PR created for review

**Testing**:
- Run pytest on modified files
- Verify optional imports still work
- Check both import-present and import-missing scenarios

**Commit Message Template**:
```
fix(t4): convert try-except imports to importlib.util.find_spec

Problem:
- Try-except ImportError patterns scattered across codebase
- Modern Python prefers importlib.util.find_spec for optional imports
- Part of T4 code quality initiative

Solution:
- Applied LibCST codemod to X files
- Converted try/except to if importlib.util.find_spec()
- Preserved all import semantics and variable assignments

Impact:
- More explicit optional dependency handling
- Easier to reason about import availability
- Consistent pattern across codebase
- All files compile and pass tests

Safety:
✅ Backups created
✅ Syntax verified
✅ Tests pass
✅ Ruff cleanup applied
```

**LUKHAS Conventions**:
- Follow T4 standards
- Include Problem/Solution/Impact in commits
- Use academic tone
- Create draft PR for review
- Comprehensive testing required

**Priority**: P1 - Code quality improvement
"""

    print("\n🚀 Creating Jules Session: T4 Try-Except Codemod")
    print("=" * 70)

    async with JulesClient() as jules:
        try:
            session = await jules.create_session(
                prompt=prompt,
                source_id="sources/github/LukhasAI/Lukhas",
                automation_mode="AUTO_CREATE_PR"
            )

            session_id = session['name'].split('/')[-1]
            print("\n✅ Created Session")
            print(f"   Session ID: {session_id}")
            print(f"   URL: https://jules.google.com/session/{session_id}")
            print("\nJules will either:")
            print("  1. Run the existing script (fastest)")
            print("  2. Enhance the codemod (if improvements needed)")
            print("  3. Create PR when complete")

            return session_id

        except Exception as e:
            print(f"\n❌ Failed: {e}")
            return None


if __name__ == "__main__":
    try:
        asyncio.run(create_codemod_session())
    except KeyboardInterrupt:
        print("\n⏸️  Cancelled")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
