#!/usr/bin/env bash
set -euo pipefail
STAMP=${STAMP:-$(date -u +%Y-%m-%dT%H%M%SZ)}
OUT=docs/audits/auditpack/$STAMP
mkdir -p "$OUT"

# 1) Health & RC soak artifacts (already generated by your runs)
cp -r docs/audits/health/latest.* "$OUT/" 2>/dev/null || true
test -d docs/audits/health/$STAMP && cp -r docs/audits/health/$STAMP/* "$OUT/" || true

# 2) OpenAPI
python3 scripts/generate_openapi.py
cp docs/openapi/lukhas-openapi.json "$OUT/"

# 3) CI & config snapshots
git rev-parse --short HEAD > "$OUT/GIT_SHA.txt"
cp .github/workflows/matriz-validate.yml "$OUT/" || true
cp .env.example "$OUT/" || true
test -f .env.audit && cp .env.audit "$OUT/" || true

# 4) Security & deps
python3 -m pip freeze > "$OUT/pip_freeze.txt" || true
( pipx run pip-audit || true ) > "$OUT/pip_audit.txt" || true

# 5) Lint & lane guard (advisory)
python3 -m ruff check lukhas core matriz --statistics --no-cache > "$OUT/ruff_statistics.txt" 2>&1 || true
PYTHONPATH=$(pwd) .venv/bin/lint-imports 2>&1 > "$OUT/lane_guard_report.txt" || echo "Lane guard check advisory - see report" >> "$OUT/lane_guard_report.txt"

# 6) Golden flows & Postman (already in repo)
test -d docs/postman && cp -r docs/postman "$OUT/postman" 2>/dev/null || true

# 7) RC Soak test results (if available)
test -d docs/audits/health/2025-10-22 && cp -r docs/audits/health/2025-10-22 "$OUT/rc_soak_results" || true

# 8) Summary
cat > "$OUT/AUDIT_README.md" <<MD
# Lukhas Audit Packet — $STAMP

- Git SHA: $(cat $OUT/GIT_SHA.txt)
- Audit Tag: audit-2025-10-22T210824Z
- OpenAPI: lukhas-openapi.json
- Health: latest.{json,md}
- Lint: ruff_statistics.txt
- Security: pip_audit.txt
- CI: matriz-validate.yml
- Env: .env.example / .env.audit
- Postman: ./postman/ (if available)
- RC Soak: ./rc_soak_results/ (if available)

## Audit Configuration

The system should be tested with the settings in \`.env.audit\`:
- LUKHAS_POLICY_MODE=strict (Guardian enforcement)
- LUKHAS_RL_KEYING=route_principal (Rate limiting)
- LUKHAS_RATE_RPS=10, LUKHAS_RATE_BURST=20
- LUKHAS_IDEMP_TTL=300 (Idempotency cache)
- LUKHAS_LOG_REDACT=1 (PII/token redaction)
- LUKHAS_TRACE_HEADERS=1 (X-Trace-Id emission)

## Auditor Quickstart

\`\`\`bash
# Start API server
uvicorn serve.main:app --host 0.0.0.0 --port 8000 --reload

# Set audit environment
export \$(grep -v '^#' .env.audit | xargs -I{} echo {})

# Verify health & headers
curl -i http://localhost:8000/healthz
curl -i -H "Authorization: Bearer test" http://localhost:8000/v1/models

# Validate OpenAPI
python3 -m pip install openapi-spec-validator
python3 - <<'PY'
import json; from openapi_spec_validator import validate
spec=json.load(open("lukhas-openapi.json"))
validate(spec); print("OpenAPI valid")
PY
\`\`\`

## Key Endpoints

- \`/healthz\` - System health with service status
- \`/v1/models\` - OpenAI-compatible models list
- \`/v1/embeddings\` - OpenAI-compatible embeddings
- \`/v1/chat/completions\` - OpenAI-compatible chat

## Expected Response Headers

All endpoints should emit:
- X-Trace-Id: Unique request trace ID
- X-Request-Id: Request identifier
- X-RateLimit-Limit: Rate limit ceiling
- X-RateLimit-Remaining: Requests remaining
- X-RateLimit-Reset: Reset timestamp

## RC Soak Test Results

Recent RC soak validation (if included):
- 100% success rate on synthetic load tests
- OpenAI-compatible endpoints functional
- Health snapshot generation working
- See rc_soak_results/RC_SOAK_TEST_RESULTS.md for details

## Validation Checklist

- [ ] OpenAPI spec validates against OpenAPI 3.1 schema
- [ ] Health endpoint returns 200 with service status
- [ ] Models endpoint returns OpenAI-compatible list format
- [ ] Rate limiting headers present on all responses
- [ ] Trace headers present for request tracking
- [ ] Guardian policy enforcement in strict mode
- [ ] Log redaction working (no API keys/tokens in logs)
- [ ] Idempotency replay headers on cache hits

MD

echo ""
echo "✅ Audit packet created at $OUT"
echo ""
echo "📦 Contents:"
ls -lh "$OUT" | tail -n +2 | awk '{printf "   - %-30s %s\n", $9, $5}'
echo ""
echo "🔗 View README: cat $OUT/AUDIT_README.md"
