#!/bin/bash

# LUKHAS AI - MongoDB Atlas Setup Guide
# GitHub Student Pack Integration
# ===================================

echo "🎓 LUKHAS AI - MongoDB Atlas Organization Setup"
echo "GitHub Student Pack: $50 Credits + $150 Certification Value"
echo "========================================================="
echo ""

echo "🏗️ RECOMMENDED ORGANIZATION STRUCTURE:"
echo ""
echo "Organization: 'LUKHAS-AI-Student-Development'"
echo "├── Project: 'lukhas-consciousness-dev' (Development)"
echo "│   └── Cluster: 'dev-consciousness-cluster' (Flex)"
echo "├── Project: 'lukhas-consciousness-prod' (Production)" 
echo "│   └── Cluster: 'prod-consciousness-cluster' (Flex)"
echo "└── Project: 'lukhas-research' (Research)"
echo "    └── Cluster: 'research-cluster' (Flex)"
echo ""

echo "📋 STEP-BY-STEP SETUP:"
echo "======================"
echo ""

echo "1️⃣ Claim GitHub Student Pack Credits"
echo "   🔗 Visit: https://www.mongodb.com/students"
echo "   👤 Sign in with GitHub account: LukhasAI"
echo "   💰 Get $50 promotional code"
echo "   ⏰ Apply within 90 days"
echo ""

echo "2️⃣ Create Organization"
echo "   📝 Name: 'LUKHAS-AI-Student-Development'"
echo "   🎯 Purpose: Educational consciousness technology development"
echo "   🔒 Billing: Apply $50 student credit here"
echo ""

echo "3️⃣ Create Development Project"
echo "   📝 Name: 'lukhas-consciousness-dev'"
echo "   🏗️ Cluster: 'dev-consciousness-cluster'"
echo "   💾 Type: M0 Flex (Free tier + student credits)"
echo "   🌍 Region: Choose closest to Azure UK South"
echo "   🔧 Sample Data: Load for testing"
echo ""

echo "4️⃣ Create Production Project"
echo "   📝 Name: 'lukhas-consciousness-prod'"
echo "   🏗️ Cluster: 'prod-consciousness-cluster'"
echo "   💾 Type: M10 Flex (Production-ready with credits)"
echo "   🌍 Region: UK South (same as Azure Container Apps)"
echo "   📊 Analytics: Enable for consciousness metrics"
echo ""

echo "5️⃣ Configure Security"
echo "   👤 Database User: 'lukhas-consciousness-user'"
echo "   🔑 Role: 'readWrite' on consciousness databases"
echo "   🌐 Network Access: Add Azure Container Apps IPs"
echo "   🔒 Authentication: Strong password + connection string"
echo ""

echo "6️⃣ Database Structure"
echo "   📚 Database: 'lukhas_consciousness'"
echo "   📄 Collections:"
echo "      • conversations (user interactions)"
echo "      • memory_folds (memory system)"
echo "      • consciousness_states (system states)"
echo "      • trinity_framework (⚛️🧠🛡️ data)"
echo "      • dream_sessions (creativity engine)"
echo "      • identity_contexts (ΛiD system)"
echo ""

echo "🎯 2025 OPTIMIZATION FEATURES:"
echo "=============================="
echo ""
echo "✅ Flex Clusters (New in 2025):"
echo "   • Cost-effective for students"
echo "   • Scales automatically"
echo "   • Perfect for consciousness data workloads"
echo ""
echo "✅ Vector Search (Beta):"
echo "   • Semantic search in consciousness conversations"
echo "   • Memory pattern matching"
echo "   • Trinity Framework similarity queries"
echo ""
echo "✅ Atlas Search:"
echo "   • Full-text search across consciousness data"
echo "   • Real-time indexing"
echo "   • Advanced filtering"
echo ""

echo "💡 LUKHAS AI SPECIFIC CONFIGURATION:"
echo "===================================="
echo ""
echo "🧠 Memory Fold Collections:"
echo "   • Indexed on: importance_score, created_at, fold_type"
echo "   • TTL: Auto-archive low-importance folds"
echo "   • Cascade Prevention: 99.7% success rate"
echo ""
echo "💬 Conversation Collections:"
echo "   • Indexed on: session_id, consciousness_level, timestamp"
echo "   • Full-text search on: message, response"
echo "   • Analytics: Real-time consciousness metrics"
echo ""
echo "⚛️🧠🛡️ Trinity Framework Collections:"
echo "   • Identity strength tracking"
echo "   • Consciousness depth measurement"
echo "   • Guardian oversight logging"
echo ""

echo "🔗 CONNECTION STRINGS:"
echo "======================"
echo ""
echo "Development:"
echo "mongodb+srv://lukhas-consciousness-user:<password>@dev-consciousness-cluster.mongodb.net/lukhas_consciousness"
echo ""
echo "Production:"
echo "mongodb+srv://lukhas-consciousness-user:<password>@prod-consciousness-cluster.mongodb.net/lukhas_consciousness"
echo ""

echo "📊 EXPECTED COSTS WITH $50 CREDIT:"
echo "=================================="
echo ""
echo "• Development Cluster (M0): FREE"
echo "• Production Cluster (M10): ~$57/month"
echo "• Research Cluster (M0): FREE"
echo "• First month: Covered by $50 credit"
echo "• Ongoing: Sustainable with project revenue"
echo ""

echo "🚀 INTEGRATION WITH LUKHAS AI:"
echo "=============================="
echo ""
echo "• Update environment variables in Azure Container Apps:"
echo "  MONGODB_ATLAS_URI=<connection_string>"
echo "  MONGODB_DATABASE=lukhas_consciousness"
echo ""
echo "• Deploy consciousness store integration:"
echo "  /integrations/mongodb_consciousness_store.py"
echo ""
echo "• Enable real-time analytics in NewRelic:"
echo "  Custom events for consciousness interactions"
echo ""

echo "✅ VERIFICATION CHECKLIST:"
echo "=========================="
echo "□ Organization created with student credits applied"
echo "□ Development project with M0 Flex cluster"
echo "□ Production project with M10 Flex cluster"
echo "□ Database users configured with proper roles"
echo "□ Network access configured for Azure IPs"
echo "□ Connection strings tested and secured"
echo "□ Collections created with optimal indexes"
echo "□ LUKHAS AI integration deployed and tested"
echo ""

echo "🎓 NEXT STEPS:"
echo "=============="
echo "1. Visit https://www.mongodb.com/students to claim credits"
echo "2. Follow this guide to set up optimal organization structure"
echo "3. Test integration with LUKHAS AI consciousness store"
echo "4. Monitor usage and consciousness analytics"
echo ""
echo "💡 Pro Tip: Start with development cluster, then scale to production"
echo "    as your consciousness technology platform grows!"