#!/usr/bin/env python3
"""
LUKHAS Owner Assignment Queue Generator

Creates GitHub issues for docs with owner: unknown, suggesting owners
based on git blame and module context.
"""
from __future__ import annotations

import json
import subprocess
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

# Constants
REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = REPO_ROOT / "docs"
INVENTORY_DIR = DOCS_ROOT / "_inventory"
MANIFEST_PATH = INVENTORY_DIR / "docs_manifest.json"


def load_manifest() -> Dict:
    """Load the documentation manifest."""
    with open(MANIFEST_PATH, encoding='utf-8') as f:
        return json.load(f)


def get_git_blame_author(file_path: Path) -> str | None:
    """Get most frequent author from git blame."""
    try:
        result = subprocess.run(
            ['git', 'blame', '--line-porcelain', str(file_path)],
            capture_output=True,
            text=True,
            timeout=5,
            cwd=REPO_ROOT
        )

        if result.returncode != 0:
            return None

        # Parse author emails
        authors = defaultdict(int)
        for line in result.stdout.split('\n'):
            if line.startswith('author-mail '):
                email = line.replace('author-mail ', '').strip('<>')
                authors[email] += 1

        if not authors:
            return None

        # Return most frequent
        return max(authors.items(), key=lambda x: x[1])[0]

    except Exception:
        return None


def suggest_owner(doc: Dict) -> str | None:
    """Suggest an owner based on git blame and module."""
    file_path = Path(doc['path'])

    # Try git blame first
    git_author = get_git_blame_author(file_path)
    if git_author and git_author not in ['noreply@anthropic.com', 'noreply@github.com']:
        # Extract username from email
        username = git_author.split('@')[0]
        if username != 'dev':
            return f"@{username}"

    # Fallback to module-based teams
    module = doc.get('module', 'unknown')
    module_teams = {
        'consciousness': '@consciousness-team',
        'identity': '@identity-team',
        'governance': '@governance-team',
        'matriz': '@matriz-team',
        'memory': '@memory-team',
        'api': '@api-team',
        'architecture': '@architecture-team',
    }

    return module_teams.get(module, '@docs-team')


def generate_issue_markdown(docs: List[Dict]) -> str:
    """Generate GitHub issue markdown for owner assignment."""
    issue = [
        "# Documentation Owner Assignment Queue",
        "",
        f"**Total docs needing owners**: {len(docs)}",
        "",
        "## Policy",
        "",
        "All documentation must have a designated owner for accountability and maintenance.",
        "- `owner: unknown` is a governance flag requiring assignment",
        "- Owners can be individuals (@username) or teams (@team-name)",
        "- Quarterly curation sprints review orphaned ownership",
        "",
        "## Assignment Process",
        "",
        "1. Review doc content and context",
        "2. Check suggested owner (from git blame or module)",
        "3. Update front-matter: `owner: @username` or `owner: team-name`",
        "4. Commit: `docs(owner): assign ownership for <module>/<file>`",
        "",
        "## Docs Requiring Owners",
        "",
    ]

    # Group by module
    by_module = defaultdict(list)
    for doc in docs:
        module = doc.get('module', 'unknown')
        by_module[module].append(doc)

    for module in sorted(by_module.keys()):
        module_docs = by_module[module]
        issue.append(f"### {module} ({len(module_docs)} docs)")
        issue.append("")

        for doc in sorted(module_docs, key=lambda d: d['path'])[:20]:  # Limit to 20 per module
            path = doc['path'].replace('docs/', '')
            suggested = suggest_owner(doc)
            issue.append(f"- [ ] [{doc['title']}]({path}) - Suggested: {suggested}")

        if len(module_docs) > 20:
            issue.append(f"  - ... and {len(module_docs) - 20} more")

        issue.append("")

    issue.extend([
        "## Progress Tracking",
        "",
        "- [ ] Review all suggestions",
        "- [ ] Assign owners to high-priority docs (architecture, api, guides)",
        "- [ ] Bulk-assign module teams for low-priority docs",
        "- [ ] Schedule quarterly review (next: 2026-01-06)",
        "",
        "---",
        "",
        "*Auto-generated by `scripts/owners_queue.py`*",
        "*Last updated: see issue timestamp*",
    ])

    return '\n'.join(issue)


def main():
    """Main workflow."""
    import sys

    print("=" * 80)
    print("LUKHAS Owner Assignment Queue Generator")
    print("=" * 80)
    print()

    # Load manifest
    print(f"📂 Loading manifest from {MANIFEST_PATH}...")
    manifest = load_manifest()
    docs = manifest['documents']

    # Filter docs with owner: unknown
    unknown_owners = [
        d for d in docs
        if d.get('owner') == 'unknown' and not d.get('redirect')
    ]

    print(f"📊 Found {len(unknown_owners)} docs with owner: unknown")
    print()

    if not unknown_owners:
        print("✅ All docs have assigned owners!")
        return

    # Generate issue markdown
    print("📝 Generating GitHub issue markdown...")
    issue_md = generate_issue_markdown(unknown_owners)

    # Write to file if --output specified
    if '--output' in sys.argv:
        output_path = DOCS_ROOT / "_generated" / "OWNER_ASSIGNMENT_QUEUE.md"
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(issue_md)
        print(f"✅ Written to {output_path}")
    else:
        # Print to stdout for GitHub CLI
        print()
        print("=" * 80)
        print("ISSUE MARKDOWN (copy to GitHub or pipe to gh)")
        print("=" * 80)
        print()
        print(issue_md)

    print()
    print("=" * 80)
    print("USAGE")
    print("=" * 80)
    print()
    print("# Save to file:")
    print("python3 scripts/owners_queue.py --output")
    print()
    print("# Create GitHub issue with gh CLI:")
    print("python3 scripts/owners_queue.py | gh issue create --title 'Docs: Owner Assignment Queue' --body-file - --label 'docs:ownership'")
    print()


if __name__ == "__main__":
    main()
