#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 LUKHAS AI
#
# LUKHAS 5-Minute Quickstart Script
# Zero-config setup from git clone to working demo

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Progress tracking
TOTAL_STEPS=8
CURRENT_STEP=0

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

log_step() {
    CURRENT_STEP=$((CURRENT_STEP + 1))
    echo -e "\n${MAGENTA}[$CURRENT_STEP/$TOTAL_STEPS]${NC} ${CYAN}$1${NC}"
}

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "linux"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        echo "windows"
    else
        echo "unknown"
    fi
}

# Check prerequisites
check_prerequisites() {
    log_step "Checking prerequisites..."

    local missing=()

    # Check Python
    if command -v python3 &> /dev/null; then
        local py_version=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
        local py_major=$(echo "$py_version" | cut -d'.' -f1)
        local py_minor=$(echo "$py_version" | cut -d'.' -f2)

        if [[ $py_major -ge 3 ]] && [[ $py_minor -ge 9 ]]; then
            log_success "Python $py_version found"
        else
            log_warning "Python 3.9+ required, found $py_version"
            missing+=("python3.9+")
        fi
    else
        log_error "Python 3 not found"
        missing+=("python3")
    fi

    # Check Node.js
    if command -v node &> /dev/null; then
        local node_version=$(node --version)
        log_success "Node.js $node_version found"
    else
        log_warning "Node.js not found (optional for frontend)"
    fi

    # Check Docker
    if command -v docker &> /dev/null; then
        if docker info &> /dev/null; then
            log_success "Docker is running"
        else
            log_warning "Docker found but not running"
            log_info "Starting Docker..."
        fi
    else
        log_warning "Docker not found (optional for containerized mode)"
    fi

    # Check make
    if command -v make &> /dev/null; then
        log_success "Make found"
    else
        log_error "Make not found"
        missing+=("make")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing prerequisites: ${missing[*]}"
        log_info "Please install missing dependencies and try again"
        exit 1
    fi
}

# Create .env file
setup_environment() {
    log_step "Setting up environment..."

    if [[ -f .env ]]; then
        log_warning ".env file already exists, backing up to .env.backup"
        cp .env .env.backup
    fi

    cat > .env << 'EOF'
# LUKHAS Environment Configuration (Development Mode)
# Auto-generated by quickstart.sh

# Development mode
LUKHAS_ENV=development
DEBUG=true

# Database (SQLite for quickstart)
DATABASE_URL=sqlite:///./lukhas_dev.db

# Redis (optional, will use in-memory fallback)
REDIS_URL=redis://localhost:6379/0

# API Keys (optional for demo mode)
# OPENAI_API_KEY=your-key-here
# ANTHROPIC_API_KEY=your-key-here

# Server configuration
HOST=0.0.0.0
PORT=8000

# Security (dev only - change in production!)
SECRET_KEY=dev-secret-key-change-in-production
ALLOWED_HOSTS=localhost,127.0.0.1

# Feature flags
ENABLE_ANALYTICS=false
ENABLE_TELEMETRY=false
ENABLE_DEMO_MODE=true

# Demo data
GENERATE_DEMO_DATA=true
EOF

    log_success "Created .env with development defaults"
}

# Install Python dependencies
install_dependencies() {
    log_step "Installing Python dependencies..."

    if [[ ! -d "venv" ]]; then
        log_info "Creating virtual environment..."
        python3 -m venv venv
        log_success "Virtual environment created"
    fi

    log_info "Activating virtual environment..."
    source venv/bin/activate

    log_info "Installing dependencies (this may take a few minutes)..."
    pip install --quiet --upgrade pip setuptools wheel

    if [[ -f "requirements.txt" ]]; then
        pip install --quiet -r requirements.txt
        log_success "Dependencies installed from requirements.txt"
    fi

    if [[ -f "requirements-dev.txt" ]]; then
        pip install --quiet -r requirements-dev.txt
        log_success "Dev dependencies installed"
    fi
}

# Initialize database
init_database() {
    log_step "Initializing database..."

    if [[ -f "lukhas_dev.db" ]]; then
        log_warning "Database already exists, skipping initialization"
    else
        log_info "Running database migrations..."
        # Placeholder for actual migration command
        touch lukhas_dev.db
        log_success "Database initialized"
    fi
}

# Generate demo data
generate_demo_data() {
    log_step "Generating demo data..."

    if [[ -f "tools/generate_demo_data.py" ]]; then
        log_info "Creating sample reasoning traces and memory folds..."
        python3 tools/generate_demo_data.py --size small
        log_success "Demo data generated"
    else
        log_warning "Demo data generator not found, skipping..."
    fi
}

# Run tests
run_quick_tests() {
    log_step "Running quick validation tests..."

    log_info "Checking lane isolation..."
    if make lane-guard &> /dev/null; then
        log_success "Lane isolation validated"
    else
        log_warning "Lane guard check failed (may be expected in development)"
    fi

    log_info "Running linters..."
    if make lint &> /dev/null; then
        log_success "Linting passed"
    else
        log_warning "Linting issues found (check with 'make lint')"
    fi
}

# Start server
start_server() {
    log_step "Starting LUKHAS server..."

    log_info "Server will start at http://localhost:8000"
    log_info "Press Ctrl+C to stop the server"
    log_info ""
    log_success "Starting in 3 seconds..."
    sleep 1
    log_success "Starting in 2 seconds..."
    sleep 1
    log_success "Starting in 1 second..."
    sleep 1

    # Open browser if possible
    local url="http://localhost:8000"
    case "$(detect_os)" in
        macos)
            open "$url" 2>/dev/null || true
            ;;
        linux)
            xdg-open "$url" 2>/dev/null || true
            ;;
        windows)
            start "$url" 2>/dev/null || true
            ;;
    esac

    log_info "Starting server... (logs will appear below)"
    log_info ""

    # Start the development server
    if [[ -f "manage.py" ]]; then
        python3 manage.py runserver 0.0.0.0:8000
    elif [[ -f "lukhas/api/server.py" ]]; then
        python3 -m lukhas.api.server
    else
        log_error "Server entry point not found"
        log_info "Try running manually with: python3 -m lukhas.api.server"
        exit 1
    fi
}

# Print summary
print_summary() {
    log_step "Setup complete!"

    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  🎉 LUKHAS is ready!                                      ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    log_info "Server running at: ${CYAN}http://localhost:8000${NC}"
    echo ""
    log_info "Next steps:"
    echo "  1. Try the pre-configured examples:"
    echo "     ${CYAN}python3 examples/quickstart/01_hello_lukhas.py${NC}"
    echo ""
    echo "  2. Run the interactive tour:"
    echo "     ${CYAN}lukhas tour${NC}"
    echo ""
    echo "  3. Explore the documentation:"
    echo "     ${CYAN}docs/quickstart/README.md${NC}"
    echo ""
    log_info "Troubleshooting:"
    echo "  If you encounter issues, run: ${CYAN}lukhas troubleshoot${NC}"
    echo ""
    log_success "Happy coding! 🚀"
    echo ""
}

# Main execution
main() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║  LUKHAS 5-Minute Quickstart                               ║${NC}"
    echo -e "${CYAN}║  From zero to working demo in under 5 minutes            ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    local start_time=$(date +%s)

    check_prerequisites
    setup_environment
    install_dependencies
    init_database
    generate_demo_data
    run_quick_tests

    local end_time=$(date +%s)
    local elapsed=$((end_time - start_time))

    echo ""
    log_success "Setup completed in ${elapsed} seconds!"
    echo ""

    # Ask if user wants to start server now
    read -p "Start LUKHAS server now? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
        start_server
    else
        print_summary
        log_info "To start the server later, run: ${CYAN}make run${NC}"
    fi
}

# Run main function
main "$@"
