#!/usr/bin/env python3
"""
LUKHAS Consciousness Types - Production Schema v1.0.0

Core dataclasses and types for the Constellation Framework consciousness system.
Implements T4/0.01% excellence standards with versioned schemas and comprehensive typing.

Constellation Framework: Flow Star (🌊), Spark Star (⚡), Oracle Star (🔮)
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Union

# Core state phases for consciousness lifecycle
StatePhase = Literal["IDLE", "AWARE", "REFLECT", "CREATE", "DREAM", "DECIDE"]

# Dream engine finite state machine phases
DreamPhase = Literal["IDLE", "ENTERING", "DREAMING", "EXITING"]

# Awareness levels for consciousness state
AwarenessLevel = Literal["minimal", "basic", "enhanced", "transcendent", "unified"]

# Anomaly severity levels
AnomalySeverity = Literal["low", "medium", "high", "critical"]

# Creative process types
CreativeProcessType = Literal["divergent", "convergent", "associative", "transformative", "synthesis"]

# Creative flow states
CreativeFlowState = Literal["blocked", "warming", "flowing", "peak", "cooling"]

# Imagination modes
ImaginationMode = Literal["visual", "conceptual", "narrative", "abstract", "hybrid"]


@dataclass
class ThoughtLoopContext:
    """Context for thought loop processing."""
    session_id: str
    query: str
    context_data: dict[str, Any]
    time_budget_ms: float
    quality_threshold: float
    tenant: str

@dataclass
class ThoughtLoopResult:
    """Result of complete thought loop processing."""
    success: bool
    thought_synthesis: Any | None
    inference_results: list[Any]
    contradiction_analysis: Any | None
    memory_validation: Any | None
    awareness_snapshot: Any | None
    meta_assessment: Any | None
    overall_quality_score: float
    reasoning_confidence: float
    contradiction_score: float
    total_processing_time_ms: float

@dataclass
class ConsciousnessState:
    """
    Core consciousness state representation.

    Tracks the current phase, awareness level, and contextual information
    for the consciousness system. Used across all consciousness engines.
    """
    awareness_level: float = 0.7
    cognitive_load: float = 0.5
    focus_intensity: float = 0.8
    memory_coherence: float = 0.9
    reasoning_depth: float = 0.7
    contradiction_tension: float = 0.2
    meta_awareness: float = 0.6
    timestamp: float = field(default_factory=time.time)
    phase: StatePhase = "IDLE"
    emotional_tone: str = "neutral"
    level: float = 0.7  # Consciousness intensity [0.0-1.0]
    ts_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    context: dict[str, Any] = field(default_factory=dict)

    # Tracking metadata
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    schema_version: str = "1.0.0"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "phase": self.phase,
            "awareness_level": self.awareness_level,
            "emotional_tone": self.emotional_tone,
            "level": self.level,
            "ts_ms": self.ts_ms,
            "context": self.context,
            "correlation_id": self.correlation_id,
            "schema_version": self.schema_version
        }


@dataclass
class AwarenessSnapshot:
    """
    Snapshot of current awareness state with drift tracking.

    Generated by AwarenessEngine.update() to capture current system
    awareness with EMA drift tracking and anomaly detection.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Core awareness metrics
    drift_ema: float = 0.0
    load_factor: float = 0.0
    anomalies: list[dict[str, Any]] = field(default_factory=list)

    # Signal processing
    signal_strength: float = 0.0
    signal_noise_ratio: float = 1.0

    # Performance metrics
    processing_time_ms: float = 0.0

    def add_anomaly(self, anomaly_type: str, severity: AnomalySeverity, details: str):
        """Add detected anomaly to snapshot"""
        anomaly = {
            "type": anomaly_type,
            "severity": severity,
            "details": details,
            "timestamp": time.time()
        }
        self.anomalies.append(anomaly)


@dataclass
class ReflectionReport:
    """
    Comprehensive reflection analysis report.

    Generated by ReflectionEngine.reflect() with coherence scoring,
    drift analysis, and anomaly detection. Schema versioned for compatibility.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Core reflection metrics
    coherence_score: float = 0.0
    drift_ema: float = 0.0
    state_delta_magnitude: float = 0.0

    # Anomaly detection
    anomalies: list[dict[str, Any]] = field(default_factory=list)
    anomaly_count: int = 0

    # Performance metrics
    reflection_duration_ms: float = 0.0
    processing_stage: str = "unknown"

    # Consciousness context
    consciousness_level: float = 0.0
    awareness_type: str = "basic"
    emotional_tone: str = "neutral"

    def add_anomaly(self, anomaly_type: str, severity: AnomalySeverity, details: str):
        """Add detected anomaly to report"""
        anomaly = {
            "type": anomaly_type,
            "severity": severity,
            "details": details,
            "timestamp": time.time()
        }
        self.anomalies.append(anomaly)
        self.anomaly_count = len(self.anomalies)


@dataclass
class DreamTrace:
    """
    Dream processing trace and consolidation artifacts.

    Generated during dream cycles to track memory consolidation,
    pattern discovery, and creative synthesis activities.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Dream session metadata
    dream_id: str = field(default_factory=lambda: f"dream_{int(time.time())}")
    phase: DreamPhase = "IDLE"
    reason: str = ""

    # Processing artifacts
    top_k_motifs: list[str] = field(default_factory=list)
    associations: list[dict[str, Any]] = field(default_factory=list)
    compression_ratio: float = 1.0

    # Performance metrics
    duration_ms: float = 0.0
    consolidation_count: int = 0

    # Memory integration
    memory_events_processed: int = 0
    memory_patterns_discovered: int = 0


@dataclass
class DecisionContext:
    """
    Context for autonomous decision making.

    Used by AutoConsciousness for action proposal and Guardian validation.
    Contains awareness state, reflection results, and proposed actions.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Input context
    consciousness_state: ConsciousnessState | None = None
    awareness_snapshot: AwarenessSnapshot | None = None
    reflection_report: ReflectionReport | None = None

    # Proposed actions
    proposed_actions: list[dict[str, Any]] = field(default_factory=list)
    confidence_score: float = 0.0

    # Guardian validation
    guardian_approved: bool = False
    guardian_response: dict[str, Any] | None = None

    def add_proposed_action(self, action_type: str, parameters: dict[str, Any], priority: str = "medium"):
        """Add a proposed action to the decision context"""
        action = {
            "type": action_type,
            "parameters": parameters,
            "priority": priority,
            "timestamp": time.time()
        }
        self.proposed_actions.append(action)


@dataclass
class CreativitySnapshot:
    """
    Snapshot of current creativity state and generated ideas.

    Generated by CreativityEngine during creative processing cycles
    to capture creative insights, associations, and imaginative constructs.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Creative flow state
    flow_state: CreativeFlowState = "blocked"
    imagination_mode: ImaginationMode = "conceptual"
    creative_energy: float = 0.0  # [0.0-1.0]

    # Generated ideas and concepts
    ideas: list[dict[str, Any]] = field(default_factory=list)
    associations: list[dict[str, Any]] = field(default_factory=list)
    transformations: list[dict[str, Any]] = field(default_factory=list)

    # Creative metrics (T4/0.01% standards)
    novelty_score: float = 0.0  # [0.0-1.0] - originality assessment
    coherence_score: float = 0.0  # [0.0-1.0] - logical consistency
    fluency_count: int = 0  # Total ideas generated
    flexibility_score: float = 0.0  # [0.0-1.0] - conceptual diversity
    elaboration_depth: float = 0.0  # [0.0-1.0] - detail richness

    # T4 excellence metrics
    convergence_efficiency: float = 0.0  # Speed to viable solutions
    divergence_breadth: float = 0.0  # Exploration scope
    synthesis_quality: float = 0.0  # Integration effectiveness

    # Processing artifacts with Guardian compliance
    inspiration_sources: list[str] = field(default_factory=list)
    creative_constraints: list[str] = field(default_factory=list)
    synthesis_patterns: list[str] = field(default_factory=list)
    guardian_approvals: list[dict[str, Any]] = field(default_factory=list)

    # Performance metrics (p95 targets)
    generation_time_ms: float = 0.0  # Target: <50ms p95
    process_efficiency: float = 0.0  # [0.0-1.0] resource utilization
    memory_pressure_score: float = 0.0  # Memory impact assessment

    # Quality assurance
    validation_checks: list[dict[str, Any]] = field(default_factory=list)
    anomaly_flags: list[str] = field(default_factory=list)

    def add_idea(self, idea_type: str, content: dict[str, Any], novelty: float = 0.0,
                 coherence: float = 0.0, guardian_approved: bool = False):
        """Add a generated idea to the snapshot with T4/0.01% validation"""
        idea = {
            "type": idea_type,
            "content": content,
            "novelty": novelty,
            "coherence": coherence,
            "guardian_approved": guardian_approved,
            "timestamp": time.time(),
            "id": str(uuid.uuid4()),
            "validation_score": (novelty + coherence) / 2.0
        }
        self.ideas.append(idea)
        self.fluency_count = len(self.ideas)

        # Update aggregate metrics
        self._update_quality_metrics()

    def add_association(self, source: str, target: str, strength: float, association_type: str = "semantic"):
        """Add a discovered association to the snapshot"""
        association = {
            "source": source,
            "target": target,
            "strength": strength,
            "type": association_type,
            "timestamp": time.time()
        }
        self.associations.append(association)

    def add_transformation(self, original: str, transformed: str, process: str, confidence: float):
        """Add a creative transformation to the snapshot"""
        transformation = {
            "original": original,
            "transformed": transformed,
            "process": process,
            "confidence": confidence,
            "timestamp": time.time()
        }
        self.transformations.append(transformation)

    def _update_quality_metrics(self):
        """Update aggregate quality metrics from ideas"""
        if not self.ideas:
            return

        # Calculate aggregate novelty and coherence
        novelties = [idea.get("novelty", 0.0) for idea in self.ideas]
        coherences = [idea.get("coherence", 0.0) for idea in self.ideas]

        self.novelty_score = sum(novelties) / len(novelties)
        self.coherence_score = sum(coherences) / len(coherences)

        # Calculate flexibility (diversity of idea types)
        idea_types = {idea.get("type", "unknown") for idea in self.ideas}
        self.flexibility_score = min(len(idea_types) / 10.0, 1.0)  # Normalize to [0,1]

        # Guardian approval rate
        approved_count = sum(1 for idea in self.ideas if idea.get("guardian_approved", False))
        approved_count / len(self.ideas) if self.ideas else 0.0

    def add_guardian_approval(self, item_id: str, approved: bool, reason: str):
        """Record Guardian approval decision"""
        approval = {
            "item_id": item_id,
            "approved": approved,
            "reason": reason,
            "timestamp": time.time()
        }
        self.guardian_approvals.append(approval)

    def add_validation_check(self, check_type: str, result: bool, details: str):
        """Add quality validation check result"""
        check = {
            "type": check_type,
            "result": result,
            "details": details,
            "timestamp": time.time()
        }
        self.validation_checks.append(check)

    def flag_anomaly(self, anomaly_type: str, description: str):
        """Flag a creative anomaly for investigation"""
        self.anomaly_flags.append(f"{anomaly_type}: {description}")


@dataclass
class CreativeTask:
    """
    A creative task or challenge for the creativity engine to process.

    Defines the creative problem space, constraints, and desired outcomes
    for the creativity engine to explore and generate solutions.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    task_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Task definition
    prompt: str = ""
    context: dict[str, Any] = field(default_factory=dict)
    constraints: list[str] = field(default_factory=list)

    # Processing preferences
    preferred_process: CreativeProcessType | None = None
    imagination_mode: ImaginationMode = "conceptual"
    target_novelty: float = 0.7
    target_coherence: float = 0.8

    # Success criteria
    min_ideas: int = 5
    max_generation_time_ms: float = 1000.0
    required_associations: int = 0

    # Inspiration sources
    seed_concepts: list[str] = field(default_factory=list)
    inspiration_domains: list[str] = field(default_factory=list)


@dataclass
class ConsciousnessMetrics:
    """
    Aggregated consciousness system metrics.

    Provides comprehensive system health and performance metrics
    for monitoring and alerting.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)

    # System health
    reflection_p95_ms: float = 0.0
    awareness_update_rate: float = 0.0
    dream_cycle_frequency: float = 0.0

    # Anomaly tracking
    total_anomalies: int = 0
    anomaly_rate_per_hour: float = 0.0

    # Performance indicators
    coherence_score_avg: float = 0.0
    drift_ema_current: float = 0.0
    system_load_factor: float = 0.0

    # Processing statistics
    tick_rate_hz: float = 0.0
    decision_latency_ms: float = 0.0
    guardian_approval_rate: float = 0.0


# Type aliases for complex types
ConsciousnessEvent = Union[AwarenessSnapshot, ReflectionReport, DreamTrace, DecisionContext]
EngineState = dict[str, Any]
SignalData = dict[str, Union[str, int, float, bool, list[Any], dict[str, Any]]]

# Constants for system configuration
DEFAULT_AWARENESS_CONFIG = {
    "drift_alpha": 0.3,
    "anomaly_threshold": 0.8,
    "load_smoothing_window": 10
}

DEFAULT_REFLECTION_CONFIG = {
    "coherence_threshold": 0.85,
    "p95_target_ms": 10.0,
    "cv_target": 0.10
}

DEFAULT_DREAM_CONFIG = {
    "max_duration_ms": 50,
    "consolidation_threshold": 100,
    "pattern_discovery_enabled": True
}

DEFAULT_CREATIVITY_CONFIG = {
    "p95_target_ms": 50.0,
    "min_novelty_threshold": 0.3,
    "min_coherence_threshold": 0.5,
    "max_ideas_per_cycle": 20,
    "guardian_approval_required": True,
    "memory_pressure_limit": 0.8,
    "quality_validation_enabled": True,
    "synthesis_depth_target": 3
}

# Export all public types
__all__ = [
    # Configuration constants
    "DEFAULT_AWARENESS_CONFIG",
    "DEFAULT_CREATIVITY_CONFIG",
    "DEFAULT_DREAM_CONFIG",
    "DEFAULT_REFLECTION_CONFIG",
    "AnomalySeverity",
    "AwarenessLevel",
    "AwarenessSnapshot",
    # Type aliases
    "ConsciousnessEvent",
    "ConsciousnessMetrics",
    # Core classes
    "ConsciousnessState",
    "CreativeFlowState",
    "CreativeProcessType",
    "CreativeTask",
    "CreativitySnapshot",
    "DecisionContext",
    "DreamPhase",
    "DreamTrace",
    "EngineState",
    "ImaginationMode",
    "ReflectionReport",
    "SignalData",
    # Enums
    "StatePhase"
]
