#!/usr/bin/env python3
"""
LUKHAS AI Database Integration Layer
Provides real-time database connectivity for all unified systems
"""

import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Optional


class LukhasDatabaseIntegration:
    """
    Active database integration for unified LUKHAS AI systems
    Provides real CRUD operations for content, users, analytics
    """

    def __init__(self, db_path: Optional[str] = None):
        if db_path is None:
            self.db_path = Path(__file__).parent.parent.parent / "data" / "lukhas_unified.db"
        else:
            self.db_path = Path(db_path)

        self.trinity_branding = "⚛️🧠🛡️ LUKHAS AI Trinity Framework"

    def get_connection(self):
        """Get database connection"""
        return sqlite3.connect(self.db_path)

    def save_generated_content(
        self,
        system_name: str,
        content_type: str,
        title: str,
        content: str,
        voice_coherence: float = 0.0,
    ) -> int:
        """Save content generated by any system to unified database"""
        conn = self.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            INSERT INTO lukhas_content
            (source_system, content_type, title, content, trinity_identity,
             trinity_consciousness, trinity_guardian, voice_coherence, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (
                system_name,
                content_type,
                title,
                content,
                "⚛️ Authentic consciousness technology identity",
                "🧠 LUKHAS AI consciousness technology platform",
                "🛡️ Ethical consciousness technology protection",
                voice_coherence,
                datetime.now().isoformat(),
            ),
        )

        content_id = cursor.lastrowid
        conn.commit()
        conn.close()

        return content_id

    def get_content_by_type(self, content_type: str, limit: int = 10) -> list[dict]:
        """Get content from database for any system to use"""
        conn = self.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT id, source_system, content_type, title, content,
                   trinity_identity, trinity_consciousness, trinity_guardian,
                   voice_coherence, created_at
            FROM lukhas_content
            WHERE content_type = ?
            ORDER BY created_at DESC
            LIMIT ?
        """,
            (content_type, limit),
        )

        rows = cursor.fetchall()
        conn.close()

        content_list = []
        for row in rows:
            content_list.append(
                {
                    "id": row[0],
                    "source_system": row[1],
                    "content_type": row[2],
                    "title": row[3],
                    "content": row[4],
                    "trinity_identity": row[5],
                    "trinity_consciousness": row[6],
                    "trinity_guardian": row[7],
                    "voice_coherence": row[8],
                    "created_at": row[9],
                }
            )

        return content_list

    def get_all_content(self, limit: int = 50) -> list[dict]:
        """Get all content for system-wide operations"""
        conn = self.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT id, source_system, content_type, title, content,
                   voice_coherence, created_at
            FROM lukhas_content
            ORDER BY created_at DESC
            LIMIT ?
        """,
            (limit,),
        )

        rows = cursor.fetchall()
        conn.close()

        return [
            {
                "id": r[0],
                "source_system": r[1],
                "content_type": r[2],
                "title": r[3],
                "content": r[4],
                "voice_coherence": r[5],
                "created_at": r[6],
            }
            for r in rows
        ]

    def update_voice_coherence(self, content_id: int, new_coherence: float):
        """Update voice coherence for content (used by voice optimizer)"""
        conn = self.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            UPDATE lukhas_content
            SET voice_coherence = ?, updated_at = ?
            WHERE id = ?
        """,
            (new_coherence, datetime.now().isoformat(), content_id),
        )

        conn.commit()
        conn.close()

    def log_system_activity(self, system_name: str, activity_type: str, details: str, metric_value: float = 0.0):
        """Log activity from any system for analytics"""
        conn = self.get_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            INSERT INTO lukhas_analytics
            (source_system, metric_type, metric_value, trinity_component, recorded_at)
            VALUES (?, ?, ?, ?, ?)
        """,
            (
                system_name,
                activity_type,
                metric_value,
                "⚛️🧠🛡️ Trinity Framework",
                datetime.now().isoformat(),
            ),
        )

        conn.commit()
        conn.close()

    def get_system_analytics(self, system_name: Optional[str] = None) -> list[dict]:
        """Get analytics for monitoring system performance"""
        conn = self.get_connection()
        cursor = conn.cursor()

        if system_name:
            cursor.execute(
                """
                SELECT source_system, metric_type, metric_value, recorded_at
                FROM lukhas_analytics
                WHERE source_system = ?
                ORDER BY recorded_at DESC
                LIMIT 100
            """,
                (system_name,),
            )
        else:
            cursor.execute("""
                SELECT source_system, metric_type, metric_value, recorded_at
                FROM lukhas_analytics
                ORDER BY recorded_at DESC
                LIMIT 100
            """)

        rows = cursor.fetchall()
        conn.close()

        return [{"system": r[0], "metric": r[1], "value": r[2], "time": r[3]} for r in rows]


# Global database instance for all systems
db = LukhasDatabaseIntegration()
