#!/usr/bin/env python3
"""
LUKHAS Module Ownership Assignment Tool

Helps assign ownership to modules based on codebase analysis and existing patterns.
Creates a workflow for manual ownership assignment.

Copyright (c) 2025 LUKHAS AI. All rights reserved.
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml


class OwnershipAssigner:
    """Assigns ownership to modules based on analysis"""

    def __init__(self, modules_dir: Path, codebase_root: Path):
        self.modules_dir = Path(modules_dir)
        self.codebase_root = Path(codebase_root)

    def analyze_ownership_patterns(self) -> dict[str, list[str]]:
        """Analyze existing ownership patterns in the codebase"""
        ownership_hints = defaultdict(list)

        # Look for existing ownership patterns
        for py_file in self.codebase_root.rglob("*.py"):
            try:
                with open(py_file, encoding="utf-8") as f:
                    content = f.read()

                # Look for author/maintainer patterns
                authors = self._extract_authors(content)

                if authors:
                    module_path = str(py_file.relative_to(self.codebase_root))
                    for author in authors:
                        ownership_hints[author].append(module_path)

            except Exception:
                continue

        return dict(ownership_hints)

    def _extract_authors(self, content: str) -> set[str]:
        """Extract author information from file content"""
        authors = set()

        # Common patterns for author attribution
        patterns = [
            r"@author\s+([A-Za-z0-9_-]+)",
            r"Author:\s+([A-Za-z0-9_-]+)",
            r"Maintainer:\s+([A-Za-z0-9_-]+)",
            r"Created by:?\s+([A-Za-z0-9_-]+)",
            r'__author__\s*=\s*["\']([^"\']+)["\']',
            r"# By:\s+([A-Za-z0-9_-]+)",
        ]

        for pattern in patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            for match in matches:
                if match not in ["TODO", "FIXME", "None", "Unknown"]:
                    authors.add(f"@{match.replace('@', '')}")

        return authors

    def suggest_owners(self) -> dict[str, str]:
        """Suggest owners for each module based on analysis"""
        self.analyze_ownership_patterns()
        suggestions = {}

        # Default ownership mapping based on module patterns
        default_owners = {
            "candidate.core": "@TechLead",
            "candidate.memory": "@Agent02",
            "candidate.consciousness": "@Agent03",
            "candidate.governance": "@Gonzalo",
            "candidate.identity": "@SecurityTeam",
            "lukhas.core": "@TechLead",
            "lukhas.governance": "@Gonzalo",
            "lukhas.identity": "@SecurityTeam",
            "branding": "@MarketingTeam",
            "products.security": "@SecurityTeam",
            "tools": "@DevOpsTeam",
            "matriz": "@ArchitectureTeam",
        }

        # Load all module schemas
        for schema_file in self.modules_dir.glob("*.yaml"):
            if schema_file.name == "module_schema_template.yaml":
                continue

            try:
                with open(schema_file) as f:
                    schema = yaml.safe_load(f)

                module_name = schema.get("identity", {}).get("name", "")

                if module_name:
                    # Try to find specific owner
                    suggested_owner = "@AutoGenerated"

                    # Check exact matches
                    if module_name in default_owners:
                        suggested_owner = default_owners[module_name]
                    else:
                        # Check prefix matches
                        for pattern, owner in default_owners.items():
                            if module_name.startswith(pattern):
                                suggested_owner = owner
                                break

                    suggestions[module_name] = suggested_owner

            except Exception:
                continue

        return suggestions

    def generate_ownership_report(self) -> str:
        """Generate ownership assignment report"""
        suggestions = self.suggest_owners()
        ownership_patterns = self.analyze_ownership_patterns()

        report = "# LUKHAS Module Ownership Assignment Report\n\n"
        report += "## Suggested Ownership Assignments\n\n"

        # Group by suggested owner
        by_owner = defaultdict(list)
        for module, owner in suggestions.items():
            by_owner[owner].append(module)

        for owner, modules in sorted(by_owner.items()):
            report += f"### {owner}\n"
            for module in sorted(modules):
                report += f"- {module}\n"
            report += "\n"

        report += "## Ownership Patterns Found in Codebase\n\n"
        for owner, files in ownership_patterns.items():
            report += f"### {owner}\n"
            report += f"Found in {len(files)} files\n"
            for file_path in files[:5]:  # Show first 5
                report += f"- {file_path}\n"
            if len(files) > 5:
                report += f"... and {len(files) - 5} more\n"
            report += "\n"

        report += "## Next Steps\n\n"
        report += "1. Review suggested assignments\n"
        report += "2. Update module schemas with actual owners\n"
        report += "3. Run: `python tools/update_module_owners.py`\n"
        report += "4. Validate: `python tools/module_schema_validator.py modules/schema_validator.json modules/`\n"

        return report

    def update_ownership(self, assignments: dict[str, str]) -> None:
        """Update module schemas with new ownership assignments"""
        updated_count = 0

        for schema_file in self.modules_dir.glob("*.yaml"):
            if schema_file.name == "module_schema_template.yaml":
                continue

            try:
                with open(schema_file) as f:
                    schema = yaml.safe_load(f)

                module_name = schema.get("identity", {}).get("name", "")

                if module_name in assignments:
                    current_owner = schema.get("ownership", {}).get("owner", "")
                    new_owner = assignments[module_name]

                    if current_owner != new_owner:
                        if "ownership" not in schema:
                            schema["ownership"] = {}
                        schema["ownership"]["owner"] = new_owner

                        with open(schema_file, "w") as f:
                            yaml.dump(schema, f, default_flow_style=False, sort_keys=False, indent=2)

                        print(f"Updated {schema_file.name}: {current_owner} → {new_owner}")
                        updated_count += 1

            except Exception as e:
                print(f"Error updating {schema_file.name}: {e}")
                continue

        print(f"\n✅ Updated ownership for {updated_count} modules")


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python assign_module_ownership.py <modules_dir> [codebase_root]")
        sys.exit(1)

    modules_dir = Path(sys.argv[1])
    codebase_root = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(".")

    print("🚀 LUKHAS Module Ownership Assignment Tool")
    print(f"Modules: {modules_dir}")
    print(f"Codebase: {codebase_root}")
    print("-" * 40)

    assigner = OwnershipAssigner(modules_dir, codebase_root)

    # Generate ownership report
    report = assigner.generate_ownership_report()
    report_file = modules_dir / "ownership_report.md"

    with open(report_file, "w") as f:
        f.write(report)

    print(f"📊 Generated ownership report: {report_file}")

    # Apply suggested ownership
    suggestions = assigner.suggest_owners()
    assigner.update_ownership(suggestions)

    print("\n🎉 Ownership assignment complete!")
    print("Review the ownership_report.md and make manual adjustments as needed.")


if __name__ == "__main__":
    main()
