#!/usr/bin/env python3
"""
tools/generate_evidence_pages.py

Reads release_artifacts/claims_registry.yaml (generated by generate_claims_registry.py)
and creates evidence page stubs under release_artifacts/evidence/<claim_id>.md when missing.

Usage:
  python3 tools/generate_evidence_pages.py
"""
import sys, os
from pathlib import Path
import yaml
import hashlib
import re

REGISTRY = Path("release_artifacts/claims_registry.yaml")
OUT_DIR = Path("release_artifacts/evidence")
TEMPLATE = Path("branding/templates/evidence_page.md")

def slugify(s):
    s = re.sub(r'[^a-z0-9\-]+','-', s.lower())
    s = re.sub(r'-+','-', s).strip('-')
    return s or "claim"

def ensure_template():
    if not TEMPLATE.exists():
        print("Missing template:", TEMPLATE)
        sys.exit(2)
    return TEMPLATE.read_text(encoding='utf-8')

def main():
    if not REGISTRY.exists():
        print("No registry found at", REGISTRY)
        sys.exit(0)
    out = yaml.safe_load(REGISTRY.read_text(encoding='utf-8'))
    claims = out.get("claims", [])
    if not claims:
        print("No claims in registry.")
        sys.exit(0)
    tpl = ensure_template()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    created = []
    for entry in claims:
        # build a unique claim id
        page = entry.get("page","unknown")
        claim_list = entry.get("claims_found",[])
        # make identifier based on page + claim snippet
        base = f"{Path(page).stem}-" + "-".join([re.sub(r'[^a-z0-9]', '', c.lower()) for c in claim_list[:2]])
        cid = slugify(base)
        outpath = OUT_DIR / f"{cid}.md"
        if outpath.exists():
            print("Exists:", outpath)
            continue
        # fill template
        fm = {
            "id": cid,
            "title": f"Evidence — {'; '.join(claim_list)}",
            "claim_text": "; ".join(claim_list),
            "domain": entry.get("domain"),
            "owner": entry.get("claims_verified_by", ["@web-architect"])[0] if entry.get("claims_verified_by") else "@web-architect",
            "last_verified": entry.get("last_reviewed") or "",
            "verified_by": entry.get("claims_verified_by") or [],
            "status": "draft",
            "artifact_links": entry.get("evidence_links") or [],
            "signature": None,
            "metadata": {
                "created_at": "", "generated_by": "generate_evidence_pages.py"
            }
        }
        # Render front-matter
        import yaml as _yaml
        front = "---\n" + _yaml.safe_dump(fm, sort_keys=False).strip() + "\n---\n\n"
        body = tpl
        # If template contains placeholders, rudimentary replace:
        body = body.replace("{{CLAIM_ID}}", cid).replace("{{SHORT_CLAIM}}", "; ".join(claim_list)[:60]).replace("{{EXACT_CLAIM_TEXT}}", "; ".join(claim_list))
        outpath.write_text(front + body, encoding='utf-8')
        created.append(outpath)
        print("Created:", outpath)
    print(f"Created {len(created)} evidence stubs in {OUT_DIR}")

if __name__ == "__main__":
    main()
