#!/usr/bin/env python3
"""
LUKHAS Consciousness Types - Production Schema v1.0.0

Core dataclasses and types for the Constellation Framework consciousness system.
Implements T4/0.01% excellence standards with versioned schemas and comprehensive typing.

Constellation Framework: Flow Star (🌊), Spark Star (⚡), Oracle Star (🔮)
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Literal, Optional, Union
from datetime import datetime, timezone
import time
import uuid

# Core state phases for consciousness lifecycle
StatePhase = Literal["IDLE", "AWARE", "REFLECT", "DREAM", "DECIDE"]

# Dream engine finite state machine phases
DreamPhase = Literal["IDLE", "ENTERING", "DREAMING", "EXITING"]

# Awareness levels for consciousness state
AwarenessLevel = Literal["minimal", "basic", "enhanced", "transcendent", "unified"]

# Anomaly severity levels
AnomalySeverity = Literal["low", "medium", "high", "critical"]


@dataclass
class ConsciousnessState:
    """
    Core consciousness state representation.

    Tracks the current phase, awareness level, and contextual information
    for the consciousness system. Used across all consciousness engines.
    """
    phase: StatePhase = "IDLE"
    awareness_level: AwarenessLevel = "basic"
    emotional_tone: str = "neutral"
    level: float = 0.7  # Consciousness intensity [0.0-1.0]
    ts_ms: int = field(default_factory=lambda: int(time.time() * 1000))
    context: Dict[str, Any] = field(default_factory=dict)

    # Tracking metadata
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    schema_version: str = "1.0.0"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization"""
        return {
            "phase": self.phase,
            "awareness_level": self.awareness_level,
            "emotional_tone": self.emotional_tone,
            "level": self.level,
            "ts_ms": self.ts_ms,
            "context": self.context,
            "correlation_id": self.correlation_id,
            "schema_version": self.schema_version
        }


@dataclass
class AwarenessSnapshot:
    """
    Snapshot of current awareness state with drift tracking.

    Generated by AwarenessEngine.update() to capture current system
    awareness with EMA drift tracking and anomaly detection.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Core awareness metrics
    drift_ema: float = 0.0
    load_factor: float = 0.0
    anomalies: List[Dict[str, Any]] = field(default_factory=list)

    # Signal processing
    signal_strength: float = 0.0
    signal_noise_ratio: float = 1.0

    # Performance metrics
    processing_time_ms: float = 0.0

    def add_anomaly(self, anomaly_type: str, severity: AnomalySeverity, details: str):
        """Add detected anomaly to snapshot"""
        anomaly = {
            "type": anomaly_type,
            "severity": severity,
            "details": details,
            "timestamp": time.time()
        }
        self.anomalies.append(anomaly)


@dataclass
class ReflectionReport:
    """
    Comprehensive reflection analysis report.

    Generated by ReflectionEngine.reflect() with coherence scoring,
    drift analysis, and anomaly detection. Schema versioned for compatibility.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Core reflection metrics
    coherence_score: float = 0.0
    drift_ema: float = 0.0
    state_delta_magnitude: float = 0.0

    # Anomaly detection
    anomalies: List[Dict[str, Any]] = field(default_factory=list)
    anomaly_count: int = 0

    # Performance metrics
    reflection_duration_ms: float = 0.0
    processing_stage: str = "unknown"

    # Consciousness context
    consciousness_level: float = 0.0
    awareness_type: str = "basic"
    emotional_tone: str = "neutral"

    def add_anomaly(self, anomaly_type: str, severity: AnomalySeverity, details: str):
        """Add detected anomaly to report"""
        anomaly = {
            "type": anomaly_type,
            "severity": severity,
            "details": details,
            "timestamp": time.time()
        }
        self.anomalies.append(anomaly)
        self.anomaly_count = len(self.anomalies)


@dataclass
class DreamTrace:
    """
    Dream processing trace and consolidation artifacts.

    Generated during dream cycles to track memory consolidation,
    pattern discovery, and creative synthesis activities.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Dream session metadata
    dream_id: str = field(default_factory=lambda: f"dream_{int(time.time())}")
    phase: DreamPhase = "IDLE"
    reason: str = ""

    # Processing artifacts
    top_k_motifs: List[str] = field(default_factory=list)
    associations: List[Dict[str, Any]] = field(default_factory=list)
    compression_ratio: float = 1.0

    # Performance metrics
    duration_ms: float = 0.0
    consolidation_count: int = 0

    # Memory integration
    memory_events_processed: int = 0
    memory_patterns_discovered: int = 0


@dataclass
class DecisionContext:
    """
    Context for autonomous decision making.

    Used by AutoConsciousness for action proposal and Guardian validation.
    Contains awareness state, reflection results, and proposed actions.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    # Input context
    consciousness_state: Optional[ConsciousnessState] = None
    awareness_snapshot: Optional[AwarenessSnapshot] = None
    reflection_report: Optional[ReflectionReport] = None

    # Proposed actions
    proposed_actions: List[Dict[str, Any]] = field(default_factory=list)
    confidence_score: float = 0.0

    # Guardian validation
    guardian_approved: bool = False
    guardian_response: Optional[Dict[str, Any]] = None

    def add_proposed_action(self, action_type: str, parameters: Dict[str, Any], priority: str = "medium"):
        """Add a proposed action to the decision context"""
        action = {
            "type": action_type,
            "parameters": parameters,
            "priority": priority,
            "timestamp": time.time()
        }
        self.proposed_actions.append(action)


@dataclass
class ConsciousnessMetrics:
    """
    Aggregated consciousness system metrics.

    Provides comprehensive system health and performance metrics
    for monitoring and alerting.
    """
    schema_version: str = "1.0.0"
    timestamp: float = field(default_factory=time.time)

    # System health
    reflection_p95_ms: float = 0.0
    awareness_update_rate: float = 0.0
    dream_cycle_frequency: float = 0.0

    # Anomaly tracking
    total_anomalies: int = 0
    anomaly_rate_per_hour: float = 0.0

    # Performance indicators
    coherence_score_avg: float = 0.0
    drift_ema_current: float = 0.0
    system_load_factor: float = 0.0

    # Processing statistics
    tick_rate_hz: float = 0.0
    decision_latency_ms: float = 0.0
    guardian_approval_rate: float = 0.0


# Type aliases for complex types
ConsciousnessEvent = Union[AwarenessSnapshot, ReflectionReport, DreamTrace, DecisionContext]
EngineState = Dict[str, Any]
SignalData = Dict[str, Union[str, int, float, bool, List[Any], Dict[str, Any]]]

# Constants for system configuration
DEFAULT_AWARENESS_CONFIG = {
    "drift_alpha": 0.3,
    "anomaly_threshold": 0.8,
    "load_smoothing_window": 10
}

DEFAULT_REFLECTION_CONFIG = {
    "coherence_threshold": 0.85,
    "p95_target_ms": 10.0,
    "cv_target": 0.10
}

DEFAULT_DREAM_CONFIG = {
    "max_duration_ms": 50,
    "consolidation_threshold": 100,
    "pattern_discovery_enabled": True
}

# Export all public types
__all__ = [
    # Enums
    "StatePhase", "DreamPhase", "AwarenessLevel", "AnomalySeverity",
    # Core classes
    "ConsciousnessState", "AwarenessSnapshot", "ReflectionReport",
    "DreamTrace", "DecisionContext", "ConsciousnessMetrics",
    # Type aliases
    "ConsciousnessEvent", "EngineState", "SignalData",
    # Configuration constants
    "DEFAULT_AWARENESS_CONFIG", "DEFAULT_REFLECTION_CONFIG", "DEFAULT_DREAM_CONFIG"
]